### ISSUE TITLE
新增按照指定字符串的顺序来排序的Comparator

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-core#18]
比如现在有一组的尺码乱序的,

```JAVA

String[] strs = { "XL", "S", "M", "XS", "S", "M", "L", "XL" };

```

现在也有固定顺序的 尺码字符串组 

```JAVA
private static final String[] REFER_ORDER_ARRAY = { "XS", "S", "M", "L", "XL" };
```

要求上面的乱序尺码按照这个尺码字符串排序

如果乱码的尺码组,有尺码不在指定的尺码组里面, 那么排在最后

**Comment by venusdrogon** [comment]
这个 `commons-collections4` 自带这个功能 

`org.apache.commons.collections4.comparators.FixedOrderComparator`

###示例 

```JAVA

    @Test
    public void testTest1(){
        String[] strs = { "XL", "S", "M", "XS", "S", "M", "L", "XL" };
        Arrays.sort(strs);
        LOGGER.debug("{}", JsonUtil.format(strs, 0, 0));

        String[] sorts = { "XS", "S", "M", "L", "XL" };

        Arrays.sort(strs, new FixedOrderComparator<String>(sorts));
        LOGGER.debug("{}", JsonUtil.format(strs, 0, 0));
    }

```

### 返回

```JAVA

20:36:39 DEBUG (FixedOrderComparatorTest.java:55) [testTest1()] ["L","M","M","S","S","XL","XL","XS"]
 20:36:39 DEBUG (FixedOrderComparatorTest.java:60) [testTest1()] ["XS","S","S","M","M","L","XL","XL"]

```

**Comment by venusdrogon** [comment]
但是 如果新增了一个不认识的 尺码 比如 XXL


```JAVA


    @Test
    public void testTest(){
        String[] strs = { "XL", "XXXL", "S", "M", "XS", "S", "M", "L", "XL", "XXL" };
        Arrays.sort(strs);
        LOGGER.debug("{}", JsonUtil.format(strs, 0, 0));

        String[] sorts = { "XS", "S", "M", "L", "XL" };

        FixedOrderComparator<String> fixedOrderComparator = new FixedOrderComparator<String>(sorts);
        Arrays.sort(strs, fixedOrderComparator);
        LOGGER.debug("{}", JsonUtil.format(strs, 0, 0));
    }

```

这时候就会抛异常 

```JAVA

java.lang.IllegalArgumentException: **Attempting to compare unknown object XXL**
	at org.apache.commons.collections4.comparators.FixedOrderComparator.compare(FixedOrderComparator.java:240)
	at java.util.TimSort.binarySort(TimSort.java:292)
	at java.util.TimSort.sort(TimSort.java:217)
	at java.util.Arrays.sort(Arrays.java:1438)
	at org.apache.commons.collections4.FixedOrderComparatorTest.testTest(FixedOrderComparatorTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)



```

**Comment by venusdrogon** [comment]
但是 如果新增了一个不认识的 尺码 比如 XXL


```JAVA


    @Test
    public void testTest(){
        String[] strs = { "XL", "XXXL", "S", "M", "XS", "S", "M", "L", "XL", "XXL" };
        Arrays.sort(strs);
        LOGGER.debug("{}", JsonUtil.format(strs, 0, 0));

        String[] sorts = { "XS", "S", "M", "L", "XL" };

        FixedOrderComparator<String> fixedOrderComparator = new FixedOrderComparator<String>(sorts);
        Arrays.sort(strs, fixedOrderComparator);
        LOGGER.debug("{}", JsonUtil.format(strs, 0, 0));
    }

```

这时候就会抛异常 

```JAVA

java.lang.IllegalArgumentException: **Attempting to compare unknown object XXL**
	at org.apache.commons.collections4.comparators.FixedOrderComparator.compare(FixedOrderComparator.java:240)
	at java.util.TimSort.binarySort(TimSort.java:292)
	at java.util.TimSort.sort(TimSort.java:217)
	at java.util.Arrays.sort(Arrays.java:1438)
	at org.apache.commons.collections4.FixedOrderComparatorTest.testTest(FixedOrderComparatorTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)



```

**Comment by venusdrogon** [comment]
对于 bean list的排序 

**参见** 


```JAVA

    @Test
    public void testFixedOrderComparatorTest(){
        Item item = new Item();
        List<Property> list = toList(
                        new Property(1L, "尺码", "M"),
                        new Property(2L, "尺码", "L"),
                        new Property(4L, "尺码", "XS"),
                        new Property(5L, "尺码", "XL"),
                        new Property(6L, "尺码", "S"),
                        new Property(7L, "尺码", "20"),
                        new Property(8L, "尺码", "16"));

        FixedOrderComparator<String> fixedOrderComparator = new FixedOrderComparator<String>(REFER_ORDER_ARRAY);
        fixedOrderComparator.setUnknownObjectBehavior(UnknownObjectBehavior.AFTER);

        Collections.sort(list, new PropertyComparator<Property>("value", fixedOrderComparator));
        item.setPropertyList(list);

        LOGGER.debug(JsonUtil.format(item));
    }


```


**返回** 


```JSON

{
        "propertyList":         [
                        {
                "name": "尺码",
                "id": 4,
                "value": "XS"
            },
                        {
                "name": "尺码",
                "id": 6,
                "value": "S"
            },
                        {
                "name": "尺码",
                "id": 1,
                "value": "M"
            },
                        {
                "name": "尺码",
                "id": 2,
                "value": "L"
            },
                        {
                "name": "尺码",
                "id": 5,
                "value": "XL"
            },
                        {
                "name": "尺码",
                "id": 7,
                "value": "20"
            },
                        {
                "name": "尺码",
                "id": 8,
                "value": "16"
            }
        ],
        "name": "",
        "id": 0
    }
 

```

**Comment by venusdrogon** [comment]
目前是否需要再封装待定

需求也不是非常迫切
