### ISSUE TITLE
 json toBean传入参数首字母为大写时转化的值为空的问题

### ISSUE THREAD

**Issue by shade41-code** [venusdrogon/feilong-core#509]
在和第三方对接的时候，对方给到的参数是json格式的，但是json字符串中每个参数的名称首字母是大写的，json字符串和实体类如下：
```
{
    "MemberNo":"11105000009",
    "Name":null,
    "Gender":"",
    "Phone":"15036334567",
    "Email":null,
    "Birthday":""
}

public class CrmMemberInfoCommand implements Serializable{
    /** 会员编号 */
    private String memberNo;

    /** 姓名/昵称 */
    private String name;

    /** 电话号码 */
    private String phone;

    /** 性别：男；女 */
    private String gender;

    /** 生日：Format：yyyy-MM-dd */
    private String birthday;

    /** 邮箱 */
    private String email;

     // setter getter
}
```

直接使用@venusdrogon feilong jar中的JsonUtil.toBean(Object json,Class<T> rootClass);
会抛出异常，例如

```
et.sf.json.JSONException: java.lang.NoSuchMethodException: Unknown property 'MemberNo' on class 'class com.baozun.store.command.crm.CrmMemberInfoCommand'
	at net.sf.json.util.PropertySetStrategy$DefaultPropertySetStrategy._setProperty(PropertySetStrategy.java:69)
	at net.sf.json.util.PropertySetStrategy$DefaultPropertySetStrategy.setProperty(PropertySetStrategy.java:60)
	at net.sf.json.util.PropertySetStrategy$DefaultPropertySetStrategy.setProperty(PropertySetStrategy.java:45)
	at com.feilong.tools.jsonlib.util.PropertyStrategyWrapper.setProperty(PropertyStrategyWrapper.java:61)
	at net.sf.json.util.PropertySetStrategy.setProperty(PropertySetStrategy.java:40)
	at net.sf.json.JSONObject.setProperty(JSONObject.java:1394)
	at net.sf.json.JSONObject.toBean(JSONObject.java:429)
	at com.baozun.store.util.LevisJsonUtil.toBean(LevisJsonUtil.java:87)
	at com.baozun.store.crm.LevisCrmBuilderTest.memberQueryTest(LevisCrmBuilderTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by shade41-code** [comment]
在网上找了之后发现，在将json转换为CrmMemberInfoCommand 对象在初始化JsonConfig的时候，需要设置JsonConfig的JavaIdentifierTransformer属性并重写JavaIdentifierTransformer对象的transformToJavaIdentifier方法，将每个参数名称首字母改为小写，事例代码如下：

```
    @Test
    public void memberQueryTest(){
        Map<String,String> map=new HashMap<String,String>();
        map.put("MemberNo", "11105000009");
        map.put("Name", "test");
        map.put("Gender", "男");
        map.put("Phone", "1501234567");
        map.put("Email", "test@qq.com");
        map.put("Birthday", "2000-01-01");
        JSONObject jsonObject = JSONObject.fromObject(map);
        JsonConfig jsonConfig = new JsonConfig();        
        jsonConfig.setJavaIdentifierTransformer(new JavaIdentifierTransformer(){
            @Override
            public String transformToJavaIdentifier(String str){
                return str.substring(0, 1).toLowerCase()+ str.substring(1);
            }
        });
        jsonConfig.setCycleDetectionStrategy(CycleDetectionStrategy.LENIENT);
        jsonConfig.setIgnoreDefaultExcludes(false);
        jsonConfig.registerJsonValueProcessor(Date.class, new DateJsonValueProcessor(DatePattern.COMMON_DATE_AND_TIME));
        jsonConfig.setAllowNonStringKeys(true);
        jsonConfig.setRootClass(CrmMemberInfoCommand.class);
        jsonConfig.setPropertySetStrategy(new PropertyStrategyWrapper(PropertySetStrategy.DEFAULT));
        CrmMemberInfoCommand crmMemberInfoCommand=(CrmMemberInfoCommand) JSONObject.toBean(jsonObject, jsonConfig);        
        LOGGER.info(JsonUtil.format(crmMemberInfoCommand));        
    }
```
输出

```
{
        "birthday": "2000-01-01",
        "phone": "1501234567",
        "email": "test@qq.com",
        "name": "test",
        "gender": "男",
        "memberNo": "11105000009"
 }
```

**Comment by venusdrogon** [comment]
net.sf.json.util.JSONUtils.convertToJavaIdentifier(String, JsonConfig)

![image](https://cloud.githubusercontent.com/assets/3479472/19854033/c530ef86-9fa7-11e6-9057-25c43447bfab.png)

↓
net.sf.json.util.JSONUtils.convertToJavaIdentifier(String, JsonConfig)

![image](https://cloud.githubusercontent.com/assets/3479472/19854047/d0c89dda-9fa7-11e6-90e1-9e6faa9eac19.png)

默认实现:

![image](https://cloud.githubusercontent.com/assets/3479472/19854067/f45b58dc-9fa7-11e6-94ad-4dcf9618d7dc.png)

**Comment by venusdrogon** [comment]
写了一个版本

```JAVA

    @Test
    public void testToBean2(){
        String json = "{'MemberNo':'11105000009','Name':null,'Gender':'','Phone':'15036334567','Email':null,'Birthday':''}";

        JsonToJavaConfig jsonToJavaConfig = new JsonToJavaConfig(CrmMemberInfoCommand.class);
        jsonToJavaConfig.setJavaIdentifierTransformer(UncapitalizeJavaIdentifierTransformer.UNCAPITALIZE);
        CrmMemberInfoCommand crmMemberInfoCommand = JsonUtil.toBean(json, jsonToJavaConfig);

        LOGGER.debug(JsonUtil.format(crmMemberInfoCommand));

    }

```

**Comment by venusdrogon** [comment]
1. net.sf.json.JsonConfig.setCycleDetectionStrategy(CycleDetectionStrategy)
2. net.sf.json.JsonConfig.setIgnoreDefaultExcludes(boolean)
3. net.sf.json.JsonConfig.registerJsonValueProcessor(Class, JsonValueProcessor)
4. net.sf.json.JsonConfig.setAllowNonStringKeys(boolean)

上述都是 jave to json 的方法 ,此处可以不使用

**Comment by venusdrogon** [comment]
单元测试

```JAVA

    @Test
    public void testToBeanWithUncapitalizeJavaIdentifierTransformer(){
        String json = "{'MemberNo':'11105000009','Name':null,'Gender':'','Phone':'15036334567','Email':null,'Birthday':''}";

        CrmMemberInfoCommand crmMemberInfoCommand = JsonUtil.toBean(json, new JsonToJavaConfig(CrmMemberInfoCommand.class, UNCAPITALIZE));

        assertThat(crmMemberInfoCommand, allOf(//
                        hasProperty("memberNo", is("11105000009")),
                        hasProperty("name", is(nullValue())),
                        hasProperty("gender", is("")),
                        hasProperty("phone", is("15036334567")),
                        hasProperty("email", is(nullValue())),
                        hasProperty("birthday", is(""))
        //        
        ));
    }

```
