### ISSUE TITLE
mvn install -f feilong-core 

### ISSUE THREAD

**Issue by yjm9898** [venusdrogon/feilong-core#594]
总是安装失败
```
Tests run: 1400, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 5.73 sec <<< FAILURE! - in com.feilong.FeiLongSuiteTests
testGetProgress[index:22:NumberUtil.toString(-88.067,"#0.00")="-88.07"](com.feilong.core.lang.numberutiltest.NumberUtilToStringParameterizedTest)  Time elapsed: 0.012 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<-88.0[7]> but was:<-88.0[6]>
	at com.feilong.core.lang.numberutiltest.NumberUtilToStringParameterizedTest.testGetProgress(NumberUtilToStringParameterizedTest.java:118)

testGetProgress[index:24:NumberUtil.toString(88.6,"#")="89"](com.feilong.core.lang.numberutiltest.NumberUtilToStringParameterizedTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<8[9]> but was:<8[8]>
	at com.feilong.core.lang.numberutiltest.NumberUtilToStringParameterizedTest.testGetProgress(NumberUtilToStringParameterizedTest.java:118)

testGetProgress[index:25:NumberUtil.toString(-88.6,"#")="-89"](com.feilong.core.lang.numberutiltest.NumberUtilToStringParameterizedTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<-8[9]> but was:<-8[8]>
	at com.feilong.core.lang.numberutiltest.NumberUtilToStringParameterizedTest.testGetProgress(NumberUtilToStringParameterizedTest.java:118)


Results :

Failed tests: 
  NumberUtilToStringParameterizedTest.testGetProgress:118 expected:<-88.0[7]> but was:<-88.0[6]>
  NumberUtilToStringParameterizedTest.testGetProgress:118 expected:<8[9]> but was:<8[8]>
  NumberUtilToStringParameterizedTest.testGetProgress:118 expected:<-8[9]> but was:<-8[8]>

Tests run: 1400, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.321 s
[INFO] Finished at: 2016-12-31T02:56:34+08:00
[INFO] Final Memory: 17M/219M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project feilong-core: There are test failures.
```

**Comment by venusdrogon** [comment]
期望见到您的回复

---

为了维护 issue, 如果 2017-02-20 还没有回复的话, 这个issue 将会关闭

**Comment by venusdrogon** [comment]
一直未见更新 先close
