### ISSUE TITLE
PropertyComparator hash判断两个对象是否相等是否太草率？

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-core#631]
![image](https://cloud.githubusercontent.com/assets/3479472/26835140/2319c880-4b0a-11e7-8834-c89b9e7b7ce9.png)

![image](https://cloud.githubusercontent.com/assets/3479472/26835170/38e51570-4b0a-11e7-97fa-4d3183162074.png)

**Comment by venusdrogon** [comment]
比如两个对象的hash值一样，返回0，还是不是被TreeSet过滤掉？
【上海】飞天奔月  22:33:10
假设 User(id 1, name =zhangsan) User(id 1, name =lisi)  
【上海】飞天奔月  22:33:28
你说的这个场景对的,  此时 他必须 实现 hashcode 方法 
【内蒙】路小磊  22:33:57
就算自己根据字段实现了hash值，碰撞概率也是有的吧
【帝都】-宁静  22:33:57
@【内蒙】路小磊 记得abc和什么是相同的hash
【上海】飞天奔月  22:34:22
对于 map /set  (就hashMap  hashSet) 而言 本身 也不会出现 相同 hashCode 的 key
【上海】飞天奔月  22:34:41
put /ad的时候 
【上海】飞天奔月  22:35:02
put /add的时候   jdk 自身就会处理 相同 hashcoe 的对象
【上海】飞天奔月  22:35:40
当然 也可能 hashcode 相同, 自己又重写了 equals 方法, 极端情况下 会有问题

**Comment by venusdrogon** [comment]
有极端的类

```JAVA
/**
 * for 极端测试
 * 
 * @author <a href="http://feitianbenyue.iteye.com/">feilong</a>
 * @since 1.10.3
 */
public class UserSameHashCode{

    /** The id. */
    private Integer id;

    /** The name. */
    private String  name;

    public UserSameHashCode(Integer id, String name){
        super();
        this.id = id;
        this.name = name;
    }

    public Integer getId(){
        return id;
    }

    public void setId(Integer id){
        this.id = id;
    }

    public String getName(){
        return name;
    }

    public void setName(String name){
        this.name = name;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode(){
        return 1;
    }
}

```


对于 以下代码 

```JAVA

 @Test
    public void testPropertyComparator3(){
        Set<UserSameHashCode> set = new TreeSet<>(new PropertyComparator<>("id"));

        set.add(new UserSameHashCode(5, "name5"));
        set.add(new UserSameHashCode(5, "name6"));

        LOGGER.debug(JsonUtil.format(set));
    }

```


明显输出的结果是 

```JAVA

42:36 DEBUG (PropertyComparatorTest.java:64) [testPropertyComparator3()] [    {
        "id": 5,
        "name": "name5"
    }]


```

**Comment by venusdrogon** [comment]
对于 TreeSet  底层使用的 TreeMap

对于 TreeMap 的put 方法 

```JAVA
 /**
     * Associates the specified value with the specified key in this map.
     * If the map previously contained a mapping for the key, the old
     * value is replaced.
     *
     * @param key key with which the specified value is to be associated
     * @param value value to be associated with the specified key
     *
     * @return the previous value associated with {@code key}, or
     *         {@code null} if there was no mapping for {@code key}.
     *         (A {@code null} return can also indicate that the map
     *         previously associated {@code null} with {@code key}.)
     * @throws ClassCastException if the specified key cannot be compared
     *         with the keys currently in the map
     * @throws NullPointerException if the specified key is null
     *         and this map uses natural ordering, or its comparator
     *         does not permit null keys
     */
    public V put(K key, V value) {
        Entry<K,V> t = root;
        if (t == null) {
            compare(key, key); // type (and possibly null) check

            root = new Entry<>(key, value, null);
            size = 1;
            modCount++;
            return null;
        }
        int cmp;
        Entry<K,V> parent;
        // split comparator and comparable paths
        Comparator<? super K> cpr = comparator;
        if (cpr != null) {
            do {
                parent = t;
                cmp = cpr.compare(key, t.key);
                if (cmp < 0)
                    t = t.left;
                else if (cmp > 0)
                    t = t.right;
                else
                    return t.setValue(value);
            } while (t != null);
        }
        else {
            if (key == null)
                throw new NullPointerException();
            Comparable<? super K> k = (Comparable<? super K>) key;
            do {
                parent = t;
                cmp = k.compareTo(t.key);
                if (cmp < 0)
                    t = t.left;
                else if (cmp > 0)
                    t = t.right;
                else
                    return t.setValue(value);
            } while (t != null);
        }
        Entry<K,V> e = new Entry<>(key, value, parent);
        if (cmp < 0)
            parent.left = e;
        else
            parent.right = e;
        fixAfterInsertion(e);
        size++;
        modCount++;
        return null;
    }

```

**Comment by venusdrogon** [comment]
所以 如果值 比较相等, 就比较 两个对象的hashCode 值 是不准确的 

应该再比较对象比较合适

**Comment by venusdrogon** [comment]
因此 修改下 


```JAVA


/**
 * for 极端测试
 * 
 * @author <a href="http://feitianbenyue.iteye.com/">feilong</a>
 * @since 1.10.3
 */
public class UserSameHashCode implements Comparable<UserSameHashCode>{

    /** The id. */
    private Integer id;

    /** The name. */
    private String  name;

    public UserSameHashCode(Integer id, String name){
        super();
        this.id = id;
        this.name = name;
    }

    public Integer getId(){
        return id;
    }

    public void setId(Integer id){
        this.id = id;
    }

    public String getName(){
        return name;
    }

    public void setName(String name){
        this.name = name;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode(){
        return 1;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Comparable#compareTo(java.lang.Object)
     */
    @Override
    public int compareTo(UserSameHashCode o){
        return CompareToBuilder.reflectionCompare(this, o);
    }

}

```

**Comment by venusdrogon** [comment]
改成 

```JAVA

    @SuppressWarnings({ "rawtypes", "unchecked" })
    private int compareWithSameValue(T t1,T t2){
        //ObjectUtils.compare(t1, t2, false)
        //如果对象实现了 Comparable 接口, 那么直接强转比较
        //return isInstance(t1, Comparable.class) ? ((Comparable) t1).compareTo(t2) : 1;
        return isInstance(t1, Comparable.class) ? ObjectUtils.compare((Comparable) t1, (Comparable) t2, false) : 1;
    }

```

 
会出现    #643   

```JAVA

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:747)
	at java.util.TimSort.mergeAt(TimSort.java:483)
	at java.util.TimSort.mergeCollapse(TimSort.java:410)
	at java.util.TimSort.sort(TimSort.java:214)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:659)
	at java.util.Collections.sort(Collections.java:217)
	at com.feilong.core.util.SortUtil.sortList(SortUtil.java:346)
	at com.feilong.core.util.SortUtil.sortMap(SortUtil.java:913)
	at com.feilong.core.util.SortUtil.sortMapByValueDesc(SortUtil.java:828)
	at com.feilong.core.util.sortutiltest.SortMapByValueDescTest.testSortByValueDesc12(SortMapByValueDescTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```
